#!/usr/bin/env node
// myco CLI — the umbrella entrypoint.
//
// Two eras of functionality live here:
//   1. Pre-fr-109 (still works, unchanged behaviour): `myco attach <id>`
//      connects an interactive terminal to a live mycod session over
//      the same /attach/<id> WebSocket the web UI uses. Designed to run
//      on the same host as mycod (e.g. inside a VS Code Remote-SSH
//      terminal).
//   2. fr-109 (skeleton for @myco/cli npm package): `myco --version`,
//      `myco --help`, `myco integrate --bash|--zsh`. Parsing logic is
//      extracted to cli/src/argv.js so tests can exercise it without
//      spawning subprocesses.
//
// Future phases (fr-110+) add: 5-rule Lacy classifier prompt-plugin,
// server tool endpoint calls, streaming chat client, VSCode bridge.
// Each subcommand slots in through parseArgv → COMMANDS dispatch here.

const fs = require('fs');
const os = require('os');
const path = require('path');
const { parseArgv, helpText, COMMANDS } = require('./src/argv');
// fr-109: `ws` is lazy-required inside attachCmd. It's only needed for
// the attach subcommand, and keeping it out of the top-level require
// means `--version` / `--help` / `integrate` all work in environments
// where cli/node_modules/ hasn't been populated yet (e.g. immediately
// after checkout, before `npm install`). Same trick myco's other
// entrypoints use.

const MYCO_HOME = process.env.MYCO_HOME || path.resolve(__dirname, '..');

// fr-109: version comes from cli/package.json so `myco --version` and
// npm publish agree on one source of truth. Cached at load-time since
// the file is tiny and doesn't change per-run.
function readCliVersion() {
  try {
    const pkg = JSON.parse(fs.readFileSync(path.join(__dirname, 'package.json'), 'utf8'));
    return String(pkg.version || '0.0.0');
  } catch { return '0.0.0'; }
}
const CLI_VERSION = readCliVersion();

function readEnvFile(p) {
  const out = {};
  try {
    const txt = fs.readFileSync(p, 'utf8');
    for (const line of txt.split('\n')) {
      const m = line.match(/^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)\s*$/);
      if (!m) continue;
      let val = m[2].trim();
      if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
        val = val.slice(1, -1);
      }
      out[m[1]] = val;
    }
  } catch {}
  return out;
}

function discover() {
  const env = readEnvFile(path.join(MYCO_HOME, '.env'));
  const tlsCert = process.env.TLS_CERT_PATH || env.TLS_CERT_PATH || path.join(MYCO_HOME, '.tls/cert.pem');
  const tls = fs.existsSync(tlsCert);
  const port = parseInt(process.env.PORT || env.PORT, 10) || (tls ? 443 : 3000);
  const me = process.env.USER || os.userInfo().username;

  let token = '';
  const tokens = process.env.MYCO_TOKENS || env.MYCO_TOKENS || '';
  for (const pair of tokens.split(',')) {
    const idx = pair.indexOf(':');
    if (idx < 1) continue;
    const u = pair.slice(0, idx).trim();
    const t = pair.slice(idx + 1).trim();
    if (u === me) { token = t; break; }
  }
  if (!token) token = process.env.MYCO_TOKEN || env.MYCO_TOKEN || '';

  return { tls, port, token, user: me };
}

// fr-109: usage error → print a friendly message + full help to stderr,
// exit 2. Pre-fr-109 this just printed 'usage: myco attach ...' — we
// widen it now that the CLI has more entry points.
function usage(msg) {
  if (msg) process.stderr.write('myco: ' + msg + '\n\n');
  process.stderr.write(helpText('myco') + '\n');
  process.exit(2);
}

// fr-109: `myco integrate --bash|--zsh` prints the ONE line the user
// puts in their shell rc file. Sourcing the resulting script activates
// the myco prompt integration. For fr-109 the script is a stub (fr-110
// fills in the Lacy 5-rule classifier + prompt hook).
function integrateCmd(target) {
  const scriptPath = path.join(__dirname, 'share', `myco.${target}`);
  if (!fs.existsSync(scriptPath)) {
    // Shouldn't happen — package.json's `files` array includes share/ —
    // but surface the error clearly if it does.
    process.stderr.write(
      `myco: integration script missing at ${scriptPath}\n` +
      `(this is a packaging bug — please file an issue at https://github.com/kkrazy/myco)\n`
    );
    process.exit(1);
  }
  // Print the source-line, plus a friendly comment header the user can
  // paste into their rc file verbatim. Stdout only — nothing on stderr
  // so shell-eval users get a clean output stream.
  process.stdout.write(
    `# myco — ${target} integration (auto-generated by \`myco integrate --${target}\`)\n` +
    `source "${scriptPath}"\n`
  );
}

function attachCmd(sessionId) {
  if (!sessionId) usage();

  // fr-109: lazy-require ws so --version / --help / integrate work
  // even when cli/node_modules/ is empty. Attach is the only path
  // that actually needs a live WebSocket dep.
  let WebSocket;
  try { WebSocket = require('ws'); }
  catch (err) {
    process.stderr.write(
      `myco: attach requires the \`ws\` package, but it's not installed.\n` +
      `Try: (cd "${path.dirname(__dirname)}/cli" && npm install)\n` +
      `Underlying error: ${err.message}\n`
    );
    process.exit(1);
  }

  const { tls, port, token } = discover();
  const wsProto = tls ? 'wss' : 'ws';
  const qs = token ? `?token=${encodeURIComponent(token)}` : '';
  const url = `${wsProto}://127.0.0.1:${port}/attach/${encodeURIComponent(sessionId)}${qs}`;

  const ws = new WebSocket(url, { rejectUnauthorized: false });

  let stdinWasRaw = false;
  let detachPrev = false;
  let exited = false;

  function cleanup(code = 0) {
    if (exited) return;
    exited = true;
    try { if (process.stdin.isTTY && stdinWasRaw) process.stdin.setRawMode(false); } catch {}
    try { process.stdin.pause(); } catch {}
    try { ws.close(); } catch {}
    process.exit(code);
  }

  process.on('SIGINT', () => { /* forward to PTY, don't exit ourselves */ });

  ws.on('open', () => {
    process.stderr.write('\x1b[2m[myco] attached — detach: Ctrl-] then q\x1b[0m\r\n');
    if (process.stdin.isTTY) {
      try { process.stdin.setRawMode(true); stdinWasRaw = true; } catch {}
    }
    process.stdin.resume();
    if (process.stdout.isTTY) {
      ws.send(JSON.stringify({ t: 'resize', cols: process.stdout.columns, rows: process.stdout.rows }));
    }
  });

  process.stdout.on('resize', () => {
    if (ws.readyState !== WebSocket.OPEN) return;
    if (process.stdout.isTTY) {
      ws.send(JSON.stringify({ t: 'resize', cols: process.stdout.columns, rows: process.stdout.rows }));
    }
  });

  process.stdin.on('data', (chunk) => {
    if (ws.readyState !== WebSocket.OPEN) return;
    const out = [];
    for (const b of chunk) {
      if (detachPrev) {
        detachPrev = false;
        if (b === 0x71 /* q */) { cleanup(0); return; }
        out.push(0x1d, b);
      } else if (b === 0x1d /* Ctrl-] */) {
        detachPrev = true;
      } else {
        out.push(b);
      }
    }
    if (!out.length) return;
    ws.send(JSON.stringify({ t: 'input', data: Buffer.from(out).toString('base64') }));
  });

  ws.on('message', (raw) => {
    let msg;
    try { msg = JSON.parse(raw.toString()); } catch { return; }
    if (msg.t === 'output' && typeof msg.data === 'string') {
      process.stdout.write(Buffer.from(msg.data, 'base64'));
    } else if (msg.t === 'exit') {
      process.stderr.write(`\r\n\x1b[2m[myco] session ended (code ${msg.code})\x1b[0m\r\n`);
      cleanup(0);
    } else if (msg.t === 'error') {
      process.stderr.write(`\r\n\x1b[31m[myco] ${msg.message}\x1b[0m\r\n`);
      cleanup(1);
    }
  });

  ws.on('close', (code) => {
    process.stderr.write(`\r\n\x1b[2m[myco] disconnected (${code})\x1b[0m\r\n`);
    cleanup(0);
  });

  ws.on('error', (err) => {
    process.stderr.write(`\r\n\x1b[31m[myco] ${err.message}\x1b[0m\r\n`);
    cleanup(1);
  });
}

// fr-109: dispatch through the pure argv parser so tests exercise the
// same routing logic humans hit. New subcommands land here as `case`
// additions; parseArgv returns a stable { command, ...opts } shape.
const parsed = parseArgv(process.argv.slice(2));
switch (parsed.command) {
  case COMMANDS.VERSION:
    process.stdout.write(CLI_VERSION + '\n');
    break;
  case COMMANDS.HELP:
    process.stdout.write(helpText('myco') + '\n');
    break;
  case COMMANDS.ATTACH:
    attachCmd(parsed.sessionId);
    break;
  case COMMANDS.INTEGRATE:
    integrateCmd(parsed.target);
    break;
  case COMMANDS.USAGE:
  default:
    usage(parsed.error);
    break;
}
